# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d8621a75b5e00c4afd09110e4b27e34096dbfe978673b41c2c13c049b4fab3586675bdd16ac86cbf614cc94996aefebcb0486d2489f10024e2ddd771bcb8864

test:
  secret_key_base: 81cfcce742bb93a188c9939397b62f5c74edcc6139e4b434a497a43ec0809c9ad27ba2323b4398ef9ba77f0a0e73e002b8eb3eaef7ea88cb50e16ce6a416d543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
